"""Freeze create-vivary's source-only legacy assets from canonical repo sources.

Thin-v0.3 wheels do not package these templates or skills. The archive remains in the
checkout only so migration classification and legacy compatibility fixtures can
recognize the old full scaffold without copying it into new adopters.

Run from anywhere:  python packages/create-vivary/tools/sync_assets.py
"""
from __future__ import annotations

import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
ASSETS = Path(__file__).resolve().parents[1] / "create_vivary_assets"

# canonical source -> bundled destination (relative to create_vivary_assets/)
SOURCES = {
    REPO_ROOT / "packages" / "strato" / "STRATO.md": "STRATO.md",
    REPO_ROOT / "packages" / "strato" / "templates": "templates",
    REPO_ROOT / "packages" / "strato" / ".claude" / "skills" / "strato": "strato-skill",
    REPO_ROOT
    / "packages"
    / "strato"
    / ".claude"
    / "skills"
    / "active-context": "active-context-skill",
    REPO_ROOT / ".claude" / "skills" / "loops": "loops-skill",
}


def sync() -> None:
    ASSETS.mkdir(parents=True, exist_ok=True)
    (ASSETS / "__init__.py").write_text(
        '"""Bundled scaffold assets for create-vivary (generated by tools/sync_assets.py)."""\n')
    for src, dst_name in SOURCES.items():
        dst = ASSETS / dst_name
        if not src.exists():
            raise SystemExit(f"sync_assets: missing canonical source {src}")
        if src.is_dir():
            if dst.exists():
                shutil.rmtree(dst)
            shutil.copytree(src, dst)
        else:
            shutil.copy2(src, dst)
        print(f"  synced {src.relative_to(REPO_ROOT)} -> create_vivary_assets/{dst_name}")


if __name__ == "__main__":
    sync()
    print("create-vivary assets synced.")
    sys.exit(0)
