"""Render and validate outcome contracts and bounded execution packets."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from urllib.parse import unquote

OUTCOME_STATES = {"planned", "in-progress", "done"}
PACKET_STATES = {"ready-for-agent", "in-progress", "needs-info", "ready-for-human", "done"}
REQUIRED_PACKET_HEADINGS = ("Goal", "Context", "Owned files", "Done condition", "Verify", "Stop conditions", "Log")
EXPECTED_SCOPES = {"S-00A"} | {f"S-{n:02}" for n in range(14)}
PRIVATE_VALUE = re.compile(r"[A-Za-z]:[\\/](?:Users|home)[\\/]|/home/[^/\s]+/|gh[pousr]_[A-Za-z0-9]{20,}")


def parse_header(body: str) -> tuple[dict[str, str], list[str]]:
    """Parse only the contiguous metadata block below a document heading."""
    fields = {}
    duplicates = []
    started = False
    for line in body.splitlines()[1:]:
        if not line.strip():
            if started:
                break
            continue
        match = re.fullmatch(r"([A-Za-z-]+): (.*)", line)
        if not match:
            break
        started = True
        name, value = match.groups()
        if name in fields:
            duplicates.append(name)
        fields[name] = value
    return fields, duplicates


def read_records(plan: Path) -> dict[str, dict]:
    records = {}
    for directory, kind in (("tickets", "outcome"), ("packets", "packet")):
        for path in sorted((plan / directory).glob("*.md")):
            body = path.read_text(encoding="utf-8")
            key = path.name.split("-", 1)[0]
            fields, duplicate_fields = parse_header(body)
            heading = re.match(r"^# (\d{2}[a-z]?):", body)
            records[key] = {"path": path, "body": body, "kind": kind, "fields": fields,
                            "title": body.splitlines()[0].removeprefix("# "), "key": key,
                            "heading_id": heading.group(1) if heading else None,
                            "duplicate_fields": duplicate_fields}
    return records


def ids(value: str) -> list[str]:
    return re.findall(r"\b\d{2}[a-z]?\b", value)


def dependencies(record: dict) -> list[str]:
    field = "Blocked-by" if record["kind"] == "outcome" else "Depends-on"
    return ids(record["fields"].get(field, ""))


def valid_names(value: str) -> bool:
    return value == "[]" or bool(re.fullmatch(r"\[[a-z][a-z0-9-]*(?:, [a-z][a-z0-9-]*)*\]", value))


def names(value: str) -> list[str]:
    if not valid_names(value) or value == "[]":
        return []
    return value[1:-1].split(", ")


def read_external_gates(plan: Path) -> tuple[dict[str, dict[str, str]], list[str]]:
    path = plan / "external-dependencies.md"
    if not path.exists():
        return {}, []
    gates = {}
    errors = []
    for section in re.split(r"(?=^## )", path.read_text(encoding="utf-8"), flags=re.M):
        if not section.startswith("## "):
            continue
        section_name = section.splitlines()[0].removeprefix("## ").strip()
        fields, duplicate_fields = parse_header(section)
        gate = fields.get("Gate", "")
        label = gate or f"section {section_name}"
        for field in duplicate_fields:
            errors.append(f"external gate {label}: duplicate metadata field {field}")
        if not gate:
            errors.append(f"external gate section {section_name}: missing Gate")
            continue
        if gate in gates:
            errors.append(f"duplicate external gate {gate}")
        else:
            gates[gate] = fields
    return gates, errors


def frontier(records: dict) -> list[str]:
    return sorted(key for key, record in records.items()
                  if record["kind"] == "packet" and record["fields"].get("Status") == "ready-for-agent"
                  and all(records.get(dep, {}).get("fields", {}).get("Status") == "done"
                          for dep in dependencies(record)))


def render_graph(plan: Path, records: dict) -> str:
    lines = ["# Vivary multi-project ticket graph", "", "Generated from outcome contracts and execution packets. Do not edit this file.", "",
             "Read [the design](design.md), [execution rules](execution-contract.md),",
             "[scope coverage](capability-matrix.md), and [current risks](audit.md).", "",
             "The 36 numbered outcomes preserve the complete product. Their dependencies",
             "gate completion. Agents execute bounded packets; a future feature or release",
             "decision does not block an independent packet. Packet dependencies gate starts.", "",
             "Frontier: " + (", ".join(frontier(records)) or "none") + ".",
             "In progress: " + (", ".join(sorted(key for key, record in records.items() if record["kind"] == "packet" and record["fields"].get("Status") == "in-progress")) or "none") + ".", "",
             "## Execution packets", "", "| Packet | Parent | Status | Start dependencies |", "| --- | --- | --- | --- |"]
    for key, record in records.items():
        if record["kind"] == "packet":
            fields = record["fields"]
            lines.append(f'| [{record["title"]}]({record["path"].relative_to(plan).as_posix()}) | {fields.get("Parent", "")} | {fields.get("Status", "")} | {fields.get("Depends-on", "")} |')
    lines += ["", "## Product outcomes", "", "| Outcome | Status | Completion dependencies |", "| --- | --- | --- |"]
    visited = set()
    ordered = []
    def visit(key):
        if key in visited or key not in records:
            return
        visited.add(key)
        for dep in dependencies(records[key]):
            visit(dep)
        ordered.append(key)
    for key, record in records.items():
        if record["kind"] == "outcome":
            visit(key)
    for key in ordered:
        record = records[key]
        if record["kind"] == "outcome":
            fields = record["fields"]
            lines.append(f'| [{record["title"]}]({record["path"].relative_to(plan).as_posix()}) | {fields.get("Status", "")} | {fields.get("Blocked-by", "")} |')
    lines += ["", "Outcome 19 also requires the held [external template program](external-dependencies.md).",
              "Optional integrations require working skip and unavailable paths. Their release",
              "coverage remains required where named; they cannot block unrelated packet starts.", "",
              "## Completion dependency view", "", "```mermaid", "graph TD"]
    for key in ordered:
        record = records[key]
        if record["kind"] != "outcome":
            continue
        lines.append(f' T{key}["{key}"]')
        lines.extend(f" T{dep} --> T{key}" for dep in dependencies(record))
    lines += ["```", "", "A completed packet does not complete its parent outcome. Attach behavioral",
              "evidence for every outcome acceptance condition before closing that outcome.", ""]
    return "\n".join(lines)


def render_index(plan: Path, records: dict) -> str:
    ready = frontier(records)
    active = sorted(key for key, record in records.items()
                    if record["kind"] == "packet" and record["fields"].get("Status") == "in-progress")

    def packet_links(keys):
        if not keys:
            return ["None."]
        return [f'- [{records[key]["title"]}]({records[key]["path"].relative_to(plan).as_posix()})'
                for key in keys]

    lines = [
        "# Current Vivary program frontier",
        "",
        "Generated from outcome contracts and execution packets. Do not edit this file.",
        "",
        "## Ready packets",
        "",
        *packet_links(ready),
        "",
        "## In-progress packets",
        "",
        *packet_links(active),
        "",
        "Read the [execution rules](execution-contract.md) before claiming a packet.",
        "Open the [full graph](graph.md) for dependencies and the [design](design.md)",
        "for product scope.",
        "",
    ]
    return "\n".join(lines)


def section(body: str, heading: str) -> str:
    match = re.search(rf"^## {re.escape(heading)}\n(.*?)(?=^## |\Z)", body, re.M | re.S)
    return match.group(1).strip() if match else ""


def evidence_receipt(record: dict, plan: Path) -> tuple[dict[str, str], list[str]] | None:
    match = re.fullmatch(r"\[[^]]+\]\(([^)#]+)(?:#[^)]*)?\)", record["fields"].get("Evidence", ""))
    if not match:
        return None
    target = (record["path"].parent / unquote(match.group(1))).resolve()
    receipts = (plan / "receipts").resolve()
    if target.suffix != ".md" or not target.is_relative_to(receipts) or not target.exists():
        return None
    return parse_header(target.read_text(encoding="utf-8"))


def json_text_values(value):
    if isinstance(value, str):
        yield value
    elif isinstance(value, (list, tuple)):
        for item in value:
            yield from json_text_values(item)
    elif isinstance(value, dict):
        for key, item in value.items():
            yield key
            yield from json_text_values(item)


def check(root: Path) -> list[str]:
    plan = root / "docs/product/multi-project"
    records = read_records(plan)
    external_gates, errors = read_external_gates(plan)
    outcomes = {key for key, rec in records.items() if rec["kind"] == "outcome"}
    expected = {f"{n:02}" for n in range(1, 37)}
    if outcomes != expected:
        errors.append(f"outcome IDs differ from 01-36: {sorted(outcomes ^ expected)}")
    paths = list((plan / "tickets").glob("*.md")) + list((plan / "packets").glob("*.md"))
    if len(paths) != len(records):
        errors.append("duplicate record ID")
    for key, record in records.items():
        fields, body, kind = record["fields"], record["body"], record["kind"]
        status = fields.get("Status")
        if "External-gates" in fields and not valid_names(fields["External-gates"]):
            errors.append(f"{key}: invalid External-gates")
        for field in record["duplicate_fields"]:
            errors.append(f"{key}: duplicate metadata field {field}")
        if record["heading_id"] != key:
            errors.append(f"{key}: heading ID does not match filename")
        if fields.get("Type") != kind:
            errors.append(f"{key}: missing or invalid Type")
        if status not in (OUTCOME_STATES if kind == "outcome" else PACKET_STATES):
            errors.append(f"{key}: invalid status {status!r}")
        edge_field = "Blocked-by" if kind == "outcome" else "Depends-on"
        if not re.fullmatch(r"\[(?:\d{2}[a-z]?(?:, \d{2}[a-z]?)*)?\]", fields.get(edge_field, "")):
            errors.append(f"{key}: invalid {edge_field}")
        if len(dependencies(record)) != len(set(dependencies(record))):
            errors.append(f"{key}: duplicate dependency")
        if kind == "packet":
            if not re.fullmatch(r"\d{2}[a-z]", key) or fields.get("Parent") not in outcomes:
                errors.append(f"{key}: invalid packet ID or parent")
            elif not key.startswith(fields["Parent"]):
                errors.append(f"{key}: packet ID does not match parent")
            for field in ("Owner", "Scope", "Timebox"):
                if not fields.get(field, "").strip():
                    errors.append(f"{key}: missing {field}")
            verification_kind = fields.get("Verification-kind")
            if verification_kind not in {"inspection", "runtime"}:
                errors.append(f"{key}: missing verification kind")
            if verification_kind == "runtime":
                blocks = re.findall(r"```console\n(.*?)```", body, re.S)
                commands = [line.strip() for block in blocks for line in block.splitlines() if line.strip()]
                if not any(not line.startswith(("git diff", "gh pr checks", "python scripts/check_multi_project_plan.py", "python scripts/check_line_endings.py")) for line in commands):
                    errors.append(f"{key}: runtime packet has only common planning checks")
            for heading in REQUIRED_PACKET_HEADINGS:
                if f"## {heading}\n" not in body:
                    errors.append(f"{key}: missing {heading}")
            if status in {"needs-info", "ready-for-human"} and not fields.get("Needs", "").strip():
                errors.append(f"{key}: waiting status requires exact Needs")
            if status in {"ready-for-agent", "in-progress"} and fields.get("Needs"):
                errors.append(f"{key}: executable packet has unresolved Needs")
        else:
            for heading in ("Goal", "Context", "Done condition", "Verify", "Log"):
                if f"## {heading}\n" not in body:
                    errors.append(f"{key}: missing {heading}")
            for dep in dependencies(record):
                if dep in records and records[dep]["kind"] != "outcome":
                    errors.append(f"{key}: outcome dependency must name an outcome: {dep}")
                if dep in records and key not in ids(records[dep]["fields"].get("Unlocks", "")):
                    errors.append(f"{key}: missing reverse Unlocks on {dep}")
            for child in ids(fields.get("Unlocks", "")):
                if child not in records or key not in dependencies(records[child]):
                    errors.append(f"{key}: inconsistent Unlocks {child}")
        if kind == "packet" and "```console\n" not in body:
            errors.append(f"{key}: missing verification commands")
        if re.search(r"(?:files|paths).*must exist before.*actionable", body, re.I):
            errors.append(f"{key}: outputs are incorrectly required before work starts")
        if status == "done":
            log = section(body, "Log")
            if not fields.get("Evidence", "").strip() or not log:
                errors.append(f"{key}: done requires evidence and verification log")
            receipt = evidence_receipt(record, plan)
            if receipt is None:
                errors.append(f"{key}: done requires linked evidence receipt")
            else:
                receipt_fields, duplicate_fields = receipt
                for field in duplicate_fields:
                    errors.append(f"{key}: evidence receipt has duplicate metadata field {field}")
                if receipt_fields.get("Evidence-record") != key:
                    errors.append(f"{key}: evidence receipt does not bind record {key}")
            if fields.get("Verification-result") != "passed":
                errors.append(f"{key}: done requires Verification-result: passed")
            if kind == "outcome" and any(records.get(dep, {}).get("fields", {}).get("Status") != "done" for dep in dependencies(record)):
                errors.append(f"{key}: done outcome has unfinished completion dependencies")
            if kind == "outcome":
                for child_key, child in records.items():
                    if child["kind"] == "packet" and child["fields"].get("Parent") == key and child["fields"].get("Status") != "done":
                        errors.append(f"{key}: done outcome has unfinished child packet {child_key}")
            for gate in names(fields.get("External-gates", "[]")):
                if external_gates.get(gate, {}).get("Status") != "done":
                    errors.append(f"{key}: unfinished external gate {gate}")
        for dep in dependencies(record):
            if dep not in records:
                errors.append(f"{key}: unknown dependency {dep}")
            elif kind == "packet" and status in {"ready-for-agent", "in-progress", "ready-for-human", "done"} and records[dep]["fields"].get("Status") != "done":
                errors.append(f"{key}: executable packet has unfinished start dependency {dep}")
    for gate, fields in external_gates.items():
        if fields.get("Status") not in {"held", "done"}:
            errors.append(f"external gate {gate}: invalid status")
        if not fields.get("Owner", "").strip():
            errors.append(f"external gate {gate}: missing owner")
        for required_by in ids(fields.get("Required-by", "")):
            record = records.get(required_by)
            if not record or record["kind"] != "outcome":
                errors.append(f"external gate {gate}: invalid owner outcome {required_by}")
            elif gate not in names(record["fields"].get("External-gates", "[]")):
                errors.append(f"{required_by}: missing required external gate {gate}")
    visited, active = set(), set()
    def visit(key):
        if key in active:
            errors.append(f"dependency cycle through {key}")
            return
        if key in visited or key not in records:
            return
        active.add(key)
        for dep in dependencies(records[key]):
            visit(dep)
        active.remove(key)
        visited.add(key)
    for key in records:
        visit(key)
    coverage_path = plan / "capability-matrix.md"
    if not coverage_path.exists():
        errors.append("missing capability coverage matrix")
    else:
        coverage = coverage_path.read_text(encoding="utf-8")
        coverage_ids = re.findall(r"^\| (\d{2}) \|", coverage, re.M)
        if set(coverage_ids) != expected or len(coverage_ids) != 36:
            errors.append("capability matrix must map each of 36 outcomes exactly once")
        outcome_cells = re.findall(r"^\| \d{2} \| ([^|]+) \|", coverage, re.M)
        scopes = set(re.findall(r"\bS-\d{2}A?\b", " ".join(outcome_cells)))
        if not EXPECTED_SCOPES <= scopes:
            errors.append(f"missing retained source scope: {sorted(EXPECTED_SCOPES - scopes)}")
    graph_path = plan / "graph.md"
    if not graph_path.exists() or graph_path.read_text(encoding="utf-8") != render_graph(plan, records):
        errors.append("graph/frontier drift: run python scripts/check_multi_project_plan.py --render")
    index_path = plan / "index.md"
    if not index_path.exists() or index_path.read_text(encoding="utf-8") != render_index(plan, records):
        errors.append("frontier index drift: run python scripts/check_multi_project_plan.py --render")
    for path in sorted(path for path in plan.rglob("*") if path.is_file()):
        try:
            body = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            if path.suffix.lower() == ".json":
                errors.append(f"{path.relative_to(root)}: invalid UTF-8 JSON")
            continue
        if path.suffix == ".md":
            for link in re.findall(r"\]\(([^)\n]+)\)", body):
                if re.match(r"(?:https?://|mailto:)", link):
                    continue
                name, _, anchor = unquote(link).partition("#")
                target = (path.parent / name).resolve() if name else path.resolve()
                if not target.is_relative_to(root.resolve()) or not target.exists():
                    errors.append(f"{path.relative_to(root)}: missing or escaping link {link}")
                elif anchor and target.suffix == ".md":
                    headings = re.findall(r"^#+ (.+)$", target.read_text(encoding="utf-8"), re.M)
                    anchors = {re.sub(r"[^\w -]", "", h.lower()).replace(" ", "-") for h in headings}
                    if anchor not in anchors:
                        errors.append(f"{path.relative_to(root)}: missing anchor {link}")
        private_value = bool(PRIVATE_VALUE.search(body))
        if path.suffix.lower() == ".json":
            try:
                decoded = json.loads(body.removeprefix("\ufeff"), object_pairs_hook=lambda pairs: pairs)
            except json.JSONDecodeError as exc:
                errors.append(f"{path.relative_to(root)}: invalid JSON: {exc.msg}")
            else:
                private_value = private_value or any(PRIVATE_VALUE.search(value) for value in json_text_values(decoded))
        if private_value:
            errors.append(f"{path.relative_to(root)}: possible private path or credential")
    return errors


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--render", action="store_true", help="regenerate the graph from outcome and packet records")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    plan = root / "docs/product/multi-project"
    if args.render:
        (plan / "graph.md").write_text(render_graph(plan, read_records(plan)), encoding="utf-8", newline="\n")
        (plan / "index.md").write_text(render_index(plan, read_records(plan)), encoding="utf-8", newline="\n")
    failures = check(root)
    for failure in failures:
        print(f"ERROR: {failure}")
    if not failures:
        print("Plan checks passed: 36 outcomes, bounded packets, dependencies, exact frontier, links and evidence requirements.")
    raise SystemExit(bool(failures))
