"""Render and validate outcome contracts and bounded execution packets."""
from __future__ import annotations

import argparse
import re
from pathlib import Path
from urllib.parse import unquote

OUTCOME_STATES = {"planned", "in-progress", "done"}
PACKET_STATES = {"ready-for-agent", "in-progress", "needs-info", "ready-for-human", "done"}
REQUIRED_PACKET_HEADINGS = ("Goal", "Context", "Owned files", "Done condition", "Verify", "Stop conditions", "Log")


def read_records(plan: Path) -> dict[str, dict]:
    records = {}
    for directory, kind in (("tickets", "outcome"), ("packets", "packet")):
        for path in sorted((plan / directory).glob("*.md")):
            body = path.read_text(encoding="utf-8")
            key = path.name.split("-", 1)[0]
            fields = dict(re.findall(r"^([A-Za-z-]+): (.*)$", body, re.M))
            records[key] = {"path": path, "body": body, "kind": kind, "fields": fields,
                            "title": body.splitlines()[0].removeprefix("# "), "key": key}
    return records


def ids(value: str) -> list[str]:
    return re.findall(r"\b\d{2}[a-z]?\b", value)


def dependencies(record: dict) -> list[str]:
    field = "Blocked-by" if record["kind"] == "outcome" else "Depends-on"
    return ids(record["fields"].get(field, ""))


def frontier(records: dict) -> list[str]:
    return sorted(key for key, record in records.items()
                  if record["kind"] == "packet" and record["fields"].get("Status") == "ready-for-agent"
                  and all(records.get(dep, {}).get("fields", {}).get("Status") == "done"
                          for dep in dependencies(record)))


def render_graph(plan: Path, records: dict) -> str:
    lines = ["# Vivary multi-project ticket graph", "", "Generated from outcome contracts and execution packets. Do not edit this file.", "",
             "Read [the design](design.md), [execution rules](execution-contract.md),",
             "[scope coverage](capability-matrix.md), and [current risks](audit.md).", "",
             "The 36 numbered outcomes preserve the complete product. Their dependencies",
             "gate completion. Agents execute bounded packets; a future feature or release",
             "decision does not block an independent packet. Packet dependencies gate starts.", "",
             "Frontier: " + (", ".join(frontier(records)) or "none") + ".",
             "In progress: " + (", ".join(sorted(key for key, record in records.items() if record["kind"] == "packet" and record["fields"].get("Status") == "in-progress")) or "none") + ".", "",
             "## Execution packets", "", "| Packet | Parent | Status | Start dependencies |", "| --- | --- | --- | --- |"]
    for key, record in records.items():
        if record["kind"] == "packet":
            fields = record["fields"]
            lines.append(f'| [{record["title"]}]({record["path"].relative_to(plan).as_posix()}) | {fields.get("Parent", "")} | {fields.get("Status", "")} | {fields.get("Depends-on", "")} |')
    lines += ["", "## Product outcomes", "", "| Outcome | Status | Completion dependencies |", "| --- | --- | --- |"]
    visited = set()
    ordered = []
    def visit(key):
        if key in visited or key not in records:
            return
        visited.add(key)
        for dep in dependencies(records[key]):
            visit(dep)
        ordered.append(key)
    for key, record in records.items():
        if record["kind"] == "outcome":
            visit(key)
    for key in ordered:
        record = records[key]
        if record["kind"] == "outcome":
            fields = record["fields"]
            lines.append(f'| [{record["title"]}]({record["path"].relative_to(plan).as_posix()}) | {fields.get("Status", "")} | {fields.get("Blocked-by", "")} |')
    lines += ["", "Outcome 19 also requires the held [external template program](external-dependencies.md).",
              "Optional integrations require working skip and unavailable paths. Their release",
              "coverage remains required where named; they cannot block unrelated packet starts.", "",
              "## Completion dependency view", "", "```mermaid", "graph TD"]
    for key in ordered:
        record = records[key]
        if record["kind"] != "outcome":
            continue
        lines.append(f' T{key}["{key}"]')
        lines.extend(f" T{dep} --> T{key}" for dep in dependencies(record))
    lines += ["```", "", "A completed packet does not complete its parent outcome. Attach behavioral",
              "evidence for every outcome acceptance condition before closing that outcome.", ""]
    return "\n".join(lines)


def check(root: Path) -> list[str]:
    plan = root / "docs/product/multi-project"
    errors = []
    records = read_records(plan)
    outcomes = {key for key, rec in records.items() if rec["kind"] == "outcome"}
    expected = {f"{n:02}" for n in range(1, 37)}
    if outcomes != expected:
        errors.append(f"outcome IDs differ from 01-36: {sorted(outcomes ^ expected)}")
    paths = list((plan / "tickets").glob("*.md")) + list((plan / "packets").glob("*.md"))
    if len(paths) != len(records):
        errors.append("duplicate record ID")
    for key, record in records.items():
        fields, body, kind = record["fields"], record["body"], record["kind"]
        status = fields.get("Status")
        if fields.get("Type") != kind:
            errors.append(f"{key}: missing or invalid Type")
        if status not in (OUTCOME_STATES if kind == "outcome" else PACKET_STATES):
            errors.append(f"{key}: invalid status {status!r}")
        edge_field = "Blocked-by" if kind == "outcome" else "Depends-on"
        if not re.fullmatch(r"\[(?:\d{2}[a-z]?(?:, \d{2}[a-z]?)*)?\]", fields.get(edge_field, "")):
            errors.append(f"{key}: invalid {edge_field}")
        if len(dependencies(record)) != len(set(dependencies(record))):
            errors.append(f"{key}: duplicate dependency")
        if kind == "packet":
            if not re.fullmatch(r"\d{2}[a-z]", key) or fields.get("Parent") not in outcomes:
                errors.append(f"{key}: invalid packet ID or parent")
            for field in ("Owner", "Scope", "Timebox"):
                if not fields.get(field, "").strip():
                    errors.append(f"{key}: missing {field}")
            verification_kind = fields.get("Verification-kind")
            if verification_kind not in {"inspection", "runtime"}:
                errors.append(f"{key}: missing verification kind")
            if verification_kind == "runtime":
                blocks = re.findall(r"```console\n(.*?)```", body, re.S)
                commands = [line.strip() for block in blocks for line in block.splitlines() if line.strip()]
                if not any(not line.startswith(("git diff", "gh pr checks", "python scripts/check_multi_project_plan.py", "python scripts/check_line_endings.py")) for line in commands):
                    errors.append(f"{key}: runtime packet has only common planning checks")
            for heading in REQUIRED_PACKET_HEADINGS:
                if f"## {heading}\n" not in body:
                    errors.append(f"{key}: missing {heading}")
            if status in {"needs-info", "ready-for-human"} and not fields.get("Needs", "").strip():
                errors.append(f"{key}: waiting status requires exact Needs")
            if status in {"ready-for-agent", "in-progress"} and fields.get("Needs"):
                errors.append(f"{key}: executable packet has unresolved Needs")
        else:
            for heading in ("Goal", "Context", "Done condition", "Verify", "Log"):
                if f"## {heading}\n" not in body:
                    errors.append(f"{key}: missing {heading}")
            for dep in dependencies(record):
                if dep in records and key not in ids(records[dep]["fields"].get("Unlocks", "")):
                    errors.append(f"{key}: missing reverse Unlocks on {dep}")
            for child in ids(fields.get("Unlocks", "")):
                if child not in records or key not in dependencies(records[child]):
                    errors.append(f"{key}: inconsistent Unlocks {child}")
        if "```console\n" not in body:
            errors.append(f"{key}: missing verification commands")
        if re.search(r"(?:files|paths).*must exist before.*actionable", body, re.I):
            errors.append(f"{key}: outputs are incorrectly required before work starts")
        if status == "done":
            if not fields.get("Evidence", "").strip() or not re.search(r"## Log\n[\s\S]*\S", body):
                errors.append(f"{key}: done requires evidence and verification log")
            if kind == "outcome" and any(records.get(dep, {}).get("fields", {}).get("Status") != "done" for dep in dependencies(record)):
                errors.append(f"{key}: done outcome has unfinished completion dependencies")
        for dep in dependencies(record):
            if dep not in records:
                errors.append(f"{key}: unknown dependency {dep}")
            elif kind == "packet" and status in {"ready-for-agent", "in-progress", "done"} and records[dep]["fields"].get("Status") != "done":
                errors.append(f"{key}: executable packet has unfinished start dependency {dep}")
    visited, active = set(), set()
    def visit(key):
        if key in active:
            errors.append(f"dependency cycle through {key}")
            return
        if key in visited or key not in records:
            return
        active.add(key)
        for dep in dependencies(records[key]):
            visit(dep)
        active.remove(key)
        visited.add(key)
    for key in records:
        visit(key)
    coverage_path = plan / "capability-matrix.md"
    if not coverage_path.exists():
        errors.append("missing capability coverage matrix")
    else:
        coverage = coverage_path.read_text(encoding="utf-8")
        coverage_ids = re.findall(r"^\| (\d{2}) \|", coverage, re.M)
        if set(coverage_ids) != expected or len(coverage_ids) != 36:
            errors.append("capability matrix must map each of 36 outcomes exactly once")
        scopes = set(re.findall(r"\bS-\d{2}A?\b", coverage))
        expected_scopes = {"S-00A"} | {f"S-{n:02}" for n in range(14)}
        if not expected_scopes <= scopes:
            errors.append(f"missing retained source scope: {sorted(expected_scopes - scopes)}")
    graph_path = plan / "graph.md"
    if not graph_path.exists() or graph_path.read_text(encoding="utf-8") != render_graph(plan, records):
        errors.append("graph/frontier drift: run python scripts/check_multi_project_plan.py --render")
    for path in sorted(plan.rglob("*.md")):
        body = path.read_text(encoding="utf-8")
        for link in re.findall(r"\]\(([^)\n]+)\)", body):
            if re.match(r"(?:https?://|mailto:)", link):
                continue
            name, _, anchor = unquote(link).partition("#")
            target = (path.parent / name).resolve() if name else path.resolve()
            if not target.is_relative_to(root.resolve()) or not target.exists():
                errors.append(f"{path.relative_to(root)}: missing or escaping link {link}")
            elif anchor and target.suffix == ".md":
                headings = re.findall(r"^#+ (.+)$", target.read_text(encoding="utf-8"), re.M)
                anchors = {re.sub(r"[^\w -]", "", h.lower()).replace(" ", "-") for h in headings}
                if anchor not in anchors:
                    errors.append(f"{path.relative_to(root)}: missing anchor {link}")
        if re.search(r"[A-Za-z]:[\\/](?:Users|home)[\\/]|/home/[^/\s]+/|gh[pousr]_[A-Za-z0-9]{20,}", body):
            errors.append(f"{path.relative_to(root)}: possible private path or credential")
    return errors


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--render", action="store_true", help="regenerate the graph from outcome and packet records")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    plan = root / "docs/product/multi-project"
    if args.render:
        (plan / "graph.md").write_text(render_graph(plan, read_records(plan)), encoding="utf-8", newline="\n")
    failures = check(root)
    for failure in failures:
        print(f"ERROR: {failure}")
    if not failures:
        print("Plan checks passed: 36 outcomes, bounded packets, dependencies, exact frontier, links and evidence requirements.")
    raise SystemExit(bool(failures))
