"""JS localeCompare replication for the workspace/capsule sort sites.

The Node reference sorts nodes, edges, claims, unknowns, and remotes with
String.prototype.localeCompare (ICU collation - NOT codepoint order: "a"
sorts before "B"). Claim/node order feeds every capsule and workspace
fingerprint, so the Python port must reproduce that ordering exactly.

The table below is an EMPIRICAL pin extracted from Node itself
(python/parity/extract_collation.mjs): a two-level UCA-style model -
primary group order, tertiary order within a group (case pairs), completely
ignorable characters skipped - verified against localeCompare over a full
pairwise probe set (~2.1M pairs) at extraction time, and re-verified
cross-language by the parity harness.

Characters OUTSIDE the pinned domain raise CollationDomainError: the port
refuses to guess ICU's order for characters the oracle never pinned (fail
loud, never silently diverge). The domain covers ASCII printable, tab/CR/LF,
and Latin-1 - everything git output, paths, facts, and claim text contain
in this system's practice.

Generated by scratchpad gen_collation_py.py from collation-table.json; do
not hand-edit the tables. Regenerate only if the Node reference's observed
collation changes (which would itself be a frozen-contract event).
"""

from __future__ import annotations

from functools import cmp_to_key

_IGNORABLE = frozenset([127, 128, 129, 130, 131, 132, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 173, 8203, 8204, 8205, 8206, 8207, 8234, 8235, 8236, 8237, 8238, 8288, 8289, 8290, 8291, 8292, 8294, 8295, 8296, 8297, 8298, 8299, 8300, 8301, 8302, 8303])

_GROUPS = (
    (9,),
    (10,),
    (11,),
    (12,),
    (13,),
    (133,),
    (8232,),
    (8233,),
    (32, 8192, 8193, 8194, 8195, 8196, 8197, 8198, 8200, 8201, 8202, 8287, 160, 8199, 8239),
    (8254,),
    (95,),
    (8215,),
    (45,),
    (8208, 8209),
    (8210,),
    (8211,),
    (8212,),
    (8213,),
    (8275,),
    (44,),
    (59,),
    (8271,),
    (58,),
    (33,),
    (8252,),
    (8265,),
    (161,),
    (63,),
    (8264,),
    (8263,),
    (191,),
    (8253,),
    (46, 8228),
    (8229,),
    (8230,),
    (183,),
    (8277,),
    (8278,),
    (8280,),
    (8281,),
    (8282,),
    (8283,),
    (8284,),
    (8285,),
    (8286,),
    (39, 8216, 8217, 8218, 8219),
    (8249,),
    (8250,),
    (34, 8220, 8221, 8222, 8223),
    (171,),
    (187,),
    (40,),
    (41,),
    (91,),
    (93,),
    (123,),
    (125,),
    (8261,),
    (8262,),
    (8214,),
    (167,),
    (182,),
    (8267,),
    (64,),
    (42,),
    (8270,),
    (8273,),
    (47,),
    (92,),
    (38,),
    (8266,),
    (35,),
    (37,),
    (8240,),
    (8241,),
    (8224,),
    (8225,),
    (8226,),
    (8227,),
    (8231,),
    (8259,),
    (8268,),
    (8269,),
    (8242,),
    (8243,),
    (8244,),
    (8279,),
    (8245,),
    (8246,),
    (8247,),
    (8248,),
    (8251,),
    (8255,),
    (8276,),
    (8256,),
    (8272,),
    (8257,),
    (8258,),
    (96,),
    (180,),
    (94,),
    (175,),
    (168,),
    (184,),
    (176,),
    (169,),
    (174,),
    (43,),
    (177,),
    (247,),
    (215,),
    (60,),
    (61,),
    (62,),
    (172,),
    (124,),
    (166,),
    (126,),
    (8274,),
    (8260,),
    (164,),
    (162,),
    (36,),
    (163,),
    (165,),
    (48,),
    (49, 185),
    (189,),
    (188,),
    (50, 178),
    (51, 179),
    (190,),
    (52,),
    (53,),
    (54,),
    (55,),
    (56,),
    (57,),
    (97, 65, 170, 225, 193, 224, 192, 259, 258, 226, 194, 229, 197, 228, 196, 227, 195, 261, 260, 257, 256),
    (230, 198),
    (98, 66),
    (99, 67, 263, 262, 265, 264, 269, 268, 267, 266, 231, 199),
    (100, 68, 271, 270, 273, 272, 240, 208),
    (101, 69, 233, 201, 232, 200, 277, 276, 234, 202, 283, 282, 235, 203, 279, 278, 281, 280, 275, 274),
    (102, 70),
    (103, 71, 287, 286, 285, 284, 289, 288, 291, 290),
    (104, 72, 293, 292, 295, 294),
    (105, 73, 237, 205, 236, 204, 301, 300, 238, 206, 239, 207, 297, 296, 304, 303, 302, 299, 298),
    (307, 306),
    (305,),
    (106, 74, 309, 308),
    (107, 75, 311, 310),
    (108, 76, 314, 313, 318, 317, 316, 315, 322, 321, 320, 319),
    (109, 77),
    (110, 78, 324, 323, 328, 327, 241, 209, 326, 325),
    (331, 330),
    (111, 79, 186, 243, 211, 242, 210, 335, 334, 244, 212, 246, 214, 337, 336, 245, 213, 248, 216, 333, 332),
    (339, 338),
    (112, 80),
    (113, 81),
    (312,),
    (114, 82, 341, 340, 345, 344, 343, 342),
    (115, 83, 347, 346, 349, 348, 353, 352, 351, 350, 383),
    (223,),
    (116, 84, 357, 356, 355, 354),
    (359, 358),
    (117, 85, 250, 218, 249, 217, 365, 364, 251, 219, 367, 366, 252, 220, 369, 368, 361, 360, 371, 370, 363, 362),
    (118, 86),
    (119, 87, 373, 372),
    (120, 88),
    (121, 89, 253, 221, 375, 374, 255, 376),
    (122, 90, 378, 377, 382, 381, 380, 379),
    (254, 222),
    (329,),
    (181,),
    (8293,),
)

_WEIGHTS = {}
for _p, _group in enumerate(_GROUPS, start=1):
    for _t, _cp in enumerate(_group, start=1):
        _WEIGHTS[_cp] = (_p, _t)


class CollationDomainError(ValueError):
    """A character outside the empirically-pinned collation domain."""


def _weight_seqs(value: str):
    primary = []
    tertiary = []
    for ch in value:
        cp = ord(ch)
        if cp in _IGNORABLE:
            continue
        try:
            p, t = _WEIGHTS[cp]
        except KeyError:
            raise CollationDomainError(
                f"character U+{cp:04X} ({ch!r}) is outside the pinned collation domain; "
                "the Node oracle's ordering for it was never extracted"
            ) from None
        primary.append(p)
        tertiary.append(t)
    return primary, tertiary


def _cmp_seq(a: list, b: list) -> int:
    for i in range(max(len(a), len(b))):
        av = a[i] if i < len(a) else 0
        bv = b[i] if i < len(b) else 0
        if av != bv:
            return -1 if av < bv else 1
    return 0


def locale_compare(a: str, b: str) -> int:
    """JS `a.localeCompare(b)` (sign only) over the pinned domain."""
    ap, at = _weight_seqs(a)
    bp, bt = _weight_seqs(b)
    return _cmp_seq(ap, bp) or _cmp_seq(at, bt)


def locale_sort_key(value: str):
    """Sort key equivalent of locale_compare for `sorted(key=...)`."""
    primary, tertiary = _weight_seqs(value)
    return (tuple(primary), tuple(tertiary))


locale_cmp_key = cmp_to_key(locale_compare)
