"""Public Core seam for governed candidate recall and caller-owned transitions."""

from __future__ import annotations

from vivary_core.recall_classify import classify_candidate
from vivary_core.recall_firewall import evaluate_candidate
from vivary_core.recall_outcomes import (
    ACCEPTED,
    ACTIVE_TRUTH_UNCHANGED,
    OUTCOMES,
    REJECTED,
    REASON_CORRECTION_INPUTS_INCOMPLETE,
    REASON_CORRECTION_NOT_AUTHORIZED,
    REASON_CORRECTION_SUBJECT_MISMATCH,
    REASON_CORRECTION_TARGET_MISMATCH,
    REASON_CORRECTION_TARGET_MISSING,
    REASON_CORROBORATION,
    REASON_EVIDENCE_NOT_FINGERPRINTED,
    REASON_EXACT_DUPLICATE,
    REASON_EXPLICIT_CORRECTION,
    REASON_IDENTITY_UNRESOLVED,
    REASON_PROVIDER_DEGRADED,
    REASON_STALE,
    REASON_VALUE_CONFLICT,
    REVIEW_REQUIRED,
    STATUS_EVALUATED,
    STATUS_PROVIDER_DEGRADED,
)
from vivary_core.recall_transition import (
    MAX_RECALL_ASSERTIONS,
    RECALL_OPERATION,
    RECALL_TRANSITION_DECISION,
    RECALL_TRANSITION_REASON,
    RECALL_TRANSITION_SCHEMA,
    project_recall_transition,
)

__all__ = [
    "classify_candidate",
    "evaluate_candidate",
    "project_recall_transition",
    "ACCEPTED",
    "REVIEW_REQUIRED",
    "REJECTED",
    "OUTCOMES",
    "ACTIVE_TRUTH_UNCHANGED",
    "STATUS_EVALUATED",
    "STATUS_PROVIDER_DEGRADED",
    "REASON_EXACT_DUPLICATE",
    "REASON_CORROBORATION",
    "REASON_EXPLICIT_CORRECTION",
    "REASON_IDENTITY_UNRESOLVED",
    "REASON_VALUE_CONFLICT",
    "REASON_STALE",
    "REASON_PROVIDER_DEGRADED",
    "REASON_EVIDENCE_NOT_FINGERPRINTED",
    "REASON_CORRECTION_TARGET_MISSING",
    "REASON_CORRECTION_SUBJECT_MISMATCH",
    "REASON_CORRECTION_TARGET_MISMATCH",
    "REASON_CORRECTION_NOT_AUTHORIZED",
    "REASON_CORRECTION_INPUTS_INCOMPLETE",
    "RECALL_TRANSITION_SCHEMA",
    "MAX_RECALL_ASSERTIONS",
    "RECALL_OPERATION",
    "RECALL_TRANSITION_DECISION",
    "RECALL_TRANSITION_REASON",
]
